project_id = "cstkeblqqyjwlrbppucu"

[functions.send-form-notification]
verify_jwt = false

[functions.migrate-advisor-images]
verify_jwt = true

[functions.send-calculator-results]
verify_jwt = false

[functions.send-life-insurance-notification]
verify_jwt = false

[functions.send-application-resume-link]
verify_jwt = false
