project_id = "cstkeblqqyjwlrbppucu"

[functions.send-form-notification]
verify_jwt = false

[functions.migrate-advisor-images]
verify_jwt = true

[functions.send-calculator-results]
verify_jwt = false

[functions.send-life-insurance-notification]
verify_jwt = false

[functions.send-application-resume-link]
verify_jwt = false

[functions.shopify-proxy]
verify_jwt = false

[functions.pipedrive-submit]
verify_jwt = false

[functions.send-business-card-order]
verify_jwt = false

[functions.send-estate-planning-notification]
verify_jwt = false

[functions.vanessa-pipedrive-submit]
verify_jwt = false

[functions.resend-life-insurance-pdf]
verify_jwt = false

[functions.create-estate-guru-checkout]
verify_jwt = false

[functions.send-estate-guru-registration]
verify_jwt = false
